const lineUp = [
  {
    name: "Diane Emerita",
    description: `Diane Emeritas äventyrliga råa sound härrör från alternativa popstrukturer, hennes klassiska pianouppväxt och en själfull sång.`,
    img: "diane-emerita.jpg",
    instagramUrl: "https://www.instagram.com/dianeemerita/",
    spotifyUrl: "https://open.spotify.com/artist/3LhfJfuhr6OZLHrpCXIyuH",
  },
  {
    name: "Tiger & Träden",
    description: `Sjunger om livet och kärleken. Melodierna och rytmerna är själens flykt från kroppen.`,
    img: "tiger.jpg",
    instagramUrl: "https://www.instagram.com/tigerochtraden/",
    spotifyUrl: "https://open.spotify.com/artist/0DTpsTLFViygxRyO94uDql",
  },
  {
    name: "Effy Simon",
    description: `Med träffsäkra melodier och en jazzinfluerad ljudbild tar Effy Simon med er på en resa tillbaka i tiden då vispopen var som bäst.`,
    img: "effy-simon.jpg",
    instagramUrl: "https://www.instagram.com/effysimonmusic/",
    spotifyUrl: "https://open.spotify.com/artist/0aAHKgdpJDLjJw2vWYsRA0",
  },
  {
    name: "Wilhelm",
    description: `Lokal förmåga med en pipa som heter duga. Slö folkmusik med texter skrivna ur en gammal mans perspektiv.`,
    img: "wilhelm.jpg",
    instagramUrl: "https://www.instagram.com/vvllhelm/",
    spotifyUrl: null,
  },
  {
    name: "Wilma Holmes",
    description: `Med en röst som doftar urskog, och ett musikaliskt landskap som varsamt skiftar mellan mörker och ljus, träffar Wilma Holmes musik rakt in i själen.`,
    img: "wilma-holmes.jpg",
    instagramUrl: "https://www.instagram.com/wilmaaholmes/",
    spotifyUrl: null,
  },
  {
    name: "Eternal Wonder",
    description: `Psytrance-producent och DJ från Torsås. Hans musik kan beskrivas som elektronisk med hög energi och psykadeliska sköna vibbar.`,
    img: "eternal-wonder.jpg",
    instagramUrl: "https://www.instagram.com/eternalwonderofficial/",
    spotifyUrl: "https://open.spotify.com/artist/2xwC2G9ccAaNFqzebuwszJ",
  },
  {
    name: "One Legged Gardener",
    description: `Ur de värmländska skogarna träder One Legged Gardener fram med texter som känns, omslutna av detaljrika gitarrarrangemang och ambienta ljudlandskap.`,
    img: "one-legged-gardener.jpg",
    instagramUrl: "https://www.instagram.com/oneleggedgardener/",
    spotifyUrl: "https://open.spotify.com/artist/28h03UnzdUxVNI7FDyfJZu",
  },
  {
    name: "Rain Stall",
    description: `Rain Stall sträcker sig efter den intimitet som kliar och vars smak skär sig.`,
    img: "rain-stall.jpg",
    instagramUrl: "https://www.instagram.com/dozingdreamflock/",
    spotifyUrl: "https://open.spotify.com/artist/6Opnw1yVHAuqSwziQdqnAd",
  },
  {
    name: "Warm Winter",
    description: `Med en blandning av 60-talets galenskap och Indiefolkens dysterhet letar Warm Winter ständigt efter balansen mellan varmt och kallt.`,
    img: "warm-winter.jpg",
    instagramUrl: "https://www.instagram.com/warmwinterwarm/",
    spotifyUrl: "https://open.spotify.com/artist/4yivpq7eOVfPYU3rzIBvvv",
  },
  {
    name: "Elin Ottilia",
    description: `Med sina rötter i indie pop/rock-scenen skriver Elin Ottilia låtar som blandar attityd, sårbarhet och närvaro.`,
    img: "elin-ottilia.jpg",
    instagramUrl: "https://www.instagram.com/elin.ottilias/",
    spotifyUrl: "https://open.spotify.com/artist/4L62RXDf8a70pfoQ9iWYkK",
  },
  {
    name: "Marcus Ekdahl",
    description: `En singer/songwriter som skriver låtar om främst sakerna i livet som inte alltid är enkla att prata om men även om fina barndomsminnen. `,
    img: "marcus.jpg",
    instagramUrl: "https://www.instagram.com/marcusekdahl/",
    spotifyUrl: "https://open.spotify.com/artist/5g7jYFCJjxBHv9To3OKxcx",
  },
];

export default lineUp;
